from oven/bun:1

workdir /use/src/app

copy ./packages ./packages
copy ./bun.lock ./bun.lock

copy ./package.json ./package.json
copy ./turbo.json ./turbo.json

copy ./apps/ws ./apps/ws


# copy . .

run bun install
# run cd packages/db && bunx prisma prisma generate && cd ../..
run bun run db:generate

expose 8081

cmd ["bun", "run", "start:websocket"]